# Generated by Django 3.0.3 on 2020-02-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_titile',
            new_name='album_title',
        ),
    ]
